export const Users = [
  {
    id: 1,
    profilePicture: "./assets/person/1.jpeg",
    username: "John Carter",
  },
  {
    id: 2,
    profilePicture: "./assets/person/2.jpeg",
    username: "Emma Stone",
  },
  {
    id: 3,
    profilePicture: "./assets/person/3.jpeg",
    username: "Liam Johnson",
  },
  {
    id: 4,
    profilePicture: "./assets/person/4.jpeg",
    username: "Olivia Brown",
  },
  {
    id: 5,
    profilePicture: "./assets/person/5.jpeg",
    username: "Noah Davis",
  },
  {
    id: 6,
    profilePicture: "./assets/person/6.jpeg",
    username: "Ava Miller",
  },
  {
    id: 7,
    profilePicture: "./assets/person/7.jpeg",
    username: "William Wilson",
  },
  {
    id: 8,
    profilePicture: "./assets/person/8.jpeg",
    username: "Sophia Moore",
  },
  {
    id: 9,
    profilePicture: "./assets/person/9.jpeg",
    username: "James Taylor",
  },
  {
    id: 10,
    profilePicture: "./assets/person/10.jpeg",
    username: "Isabella Anderson",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "./assets/post/1.jpeg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    desc: "Sunny day at the beach — recharge mode.",
    photo: "./assets/post/2.jpeg",
    date: "20 mins ago",
    userId: 2,
    like: 58,
    comment: 12,
  },
  {
    id: 3,
    desc: "New cafe discovery: best espresso in town.",
    photo: "./assets/post/3.jpeg",
    date: "1 hour ago",
    userId: 3,
    like: 24,
    comment: 4,
  },
  {
    id: 4,
    desc: "Hiking adventures with great company.",
    photo: "./assets/post/4.jpeg",
    date: "2 hours ago",
    userId: 4,
    like: 76,
    comment: 19,
  },
  {
    id: 5,
    desc: "Home cooking experiment turned out amazing!",
    photo: "./assets/post/5.jpeg",
    date: "Yesterday",
    userId: 5,
    like: 134,
    comment: 27,
  },
  {
    id: 6,
    desc: "Late night coding session — nearly done.",
    photo: "./assets/post/6.jpeg",
    date: "2 days ago",
    userId: 6,
    like: 45,
    comment: 8,
  },
  {
    id: 7,
    desc: "City lights and good vibes.",
    photo: "./assets/post/7.jpeg",
    date: "3 days ago",
    userId: 7,
    like: 98,
    comment: 22,
  },
  {
    id: 8,
    desc: "Weekend getaway — nature reset.",
    photo: "./assets/post/8.jpeg",
    date: "1 week ago",
    userId: 8,
    like: 64,
    comment: 11,
  },
  {
    id: 9,
    desc: "Throwback to this amazing concert.",
    photo: "./assets/post/9.jpeg",
    date: "2 weeks ago",
    userId: 9,
    like: 210,
    comment: 45,
  },
  {
    id: 10,
    desc: "Finished a new painting today — feeling proud.",
    photo: "./assets/post/10.jpeg",
    date: "1 month ago",
    userId: 10,
    like: 88,
    comment: 16,
  },
];
